name: Go

on:
  pull_request:
    branches: [ "*" ]
  push:
    # branches:
    # - "gh-readonly-queue/**/*"

jobs:
  testGo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Golang caches
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: run go tests
      run: |
        go test -v ./...
      env:
        RUN_INTEGRATION_TESTS: true

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: testGo
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.8

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::891612575757:role/madi-dine-service-admin
        aws-region: eu-west-3

    - name: Initialize Terraform
      run: terraform -chdir=cloud init

    - name: Apply Terraform
      run: terraform -chdir=cloud apply -auto-approve
